version: '3'

services:
  traefik:
    image: traefik:v2.3.6
    restart: always
    command:
      - --accesslog
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend
    ports:
      - 81:80
      - 8080:8080

  container1:
    build:
      context: ./
      dockerfile: Dockerfile1
    labels:
      - traefik.enable=true
      - "traefik.http.routers.container1.rule=(Host(`app.localhost`))"
      - "traefik.http.routers.container1.rule=(Host(`app.localhost`) && PathPrefix(`/container1`))"
    networks:
      - frontend 
    ports:
      - 8001:8001

  container2:
    build:
      context: ./
      dockerfile: Dockerfile2
    labels:
      - traefik.enable=true
      - "traefik.http.routers.container2.rule=(Host(`app.localhost`) && PathPrefix(`/container2`))"
    networks:
      - frontend
    ports:
      - 8002:8002

volumes:
  volum:
networks:
  frontend:
    driver: bridge
